name:                pure-clj
version:             0.1.0.0
github:              "githubuser/pure-clj"
license:             BSD3
author:              "Islon Scherer"
maintainer:          "islonscherer@gmail.com"
copyright:           "2018 Islon Scherer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pure-clj#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - base-compat >= 0.6.0
  - boxes >=0.1.4 && <0.2.0
  - bytestring
  - hspec
  - monad-control >= 1.0.0.0 && < 1.1
  - mtl
  - pattern-arrows
  - text
  - transformers
  - vector

library:
  source-dirs: src
  ghc-options: -Wall -O2
  default-extensions:
    - DeriveFunctor
    - NoImplicitPrelude
    - OverloadedStrings
    - RankNTypes
    - ScopedTypeVariables

executables:
  pursclj:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-wl-pprint
    - directory
    - filepath
    - Glob
    - optparse-applicative
    - process
    - pure-clj

tests:
  pure-clj-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pure-clj
    - hspec
